// let data = [
// 	{
// 		id : 1,
// 		photo: './photos/1.jpg',
// 		brand : 'Бренд',
// 		type : 'Кофта',
// 		color : 'Зеленая',
// 		season : 'Осень/весна',
// 		useDate : 'Никогда',
// 		liked : false,
// 	},
// 	{
// 		id : 2,
// 		photo: './photos/2.jpg',
// 		brand : 'Бренд',
// 		type : 'Платье',
// 		color : 'Коричневое',
// 		season : 'Лето',
// 		useDate : 'Никогда',
// 		liked : false,
// 	},
// 	{
// 		id : 3,
// 		photo: './photos/3.jpg',
// 		brand : 'Бренд',
// 		type : 'Платье',
// 		color : 'Синее',
// 		season : 'Лето',
// 		useDate : 'Никогда',
// 		liked : false,
// 	},
// 	{
// 		id : 4,
// 		photo: './photos/4.jpg',
// 		brand : 'Бренд',
// 		type : 'Футболка',
// 		color : 'Белая',
// 		season : 'Лето',
// 		useDate : 'Никогда',
// 		liked : false,
// 	},
// 	{
// 		id : 5,
// 		photo: './photos/1.jpg',
// 		brand : 'Бренд',
// 		type : 'Рубашка',
// 		color : 'Фиолетовая',
// 		season : 'Лето',
// 		useDate : 'Никогда',
// 		liked : false,
// 	},
// 	{
// 		id : 6,
// 		photo: './photos/6.jpg',
// 		brand : 'Бренд',
// 		type : 'Рубашка',
// 		color : 'Фиолетовая',
// 		season : 'Лето',
// 		useDate : 'Никогда',
// 		liked : false,
// 	},
// ]
